### ISSUE TITLE
CentOS5 image there isn't python-pip

### ISSUE THREAD

**Issue by weldpua2008** [smiller171/ansible-docker-images#11]
Hi,
https://github.com/smiller171/ansible-docker-images/blob/master/centos/5/Dockerfile#L9

There isn't python-pip in repo.
PS:
I am using installation of python 2.7 from the source:
https://github.com/weldpua2008/docker-ansible/blob/ansible_1.9.2/centos/5/Dockerfile#L13

**Comment by smiller171** [comment]
Sorry I didn't see this sooner. Looking into it now

**Comment by smiller171** [comment]
Thanks for the tips. Fixed the build and rebuilt in Docker Hub
